import { useState } from 'react';
import useWeb3forms from '@web3forms/react';
import { ArrowUpRight } from 'lucide-react';

const Contact = () => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [sent, setSent] = useState(false);
  const { submit } = useWeb3forms({ access_key: '39716599-07e6-4701-a5f1-40c441460122', settings: { from_name: 'Portfolio Contact Form', subject: 'New Contact Form Submission from Portfolio' }, onSuccess: () => { setSent(true); setIsSubmitting(false); }, onError: () => setIsSubmitting(false) });
  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setIsSubmitting(true); await submit(Object.fromEntries(new FormData(event.currentTarget).entries())); };
  return <section id="contact" className="section"><div className="section-inner"><div className="section-heading"><div className="section-kicker">05 / ping priyanshu</div><div><h2>Let’s make something dependable.</h2><p>Have a platform to steady, a migration to plan, or simply a good problem? I’m listening.</p></div></div><div className="contact-grid"><div><p className="contact-intro">Available for freelance DevOps and SRE projects, consulting, and thoughtful infrastructure work.</p><div className="contact-meta"><a href="mailto:priyanshu.txt@gmail.com">priyanshu.txt@gmail.com <ArrowUpRight size={14} /></a><span>Gurugram, Haryana, India</span><a href="https://github.com/pkdeva" target="_blank" rel="noopener noreferrer">github.com/pkdeva <ArrowUpRight size={14} /></a><a href="https://linkedin.com/in/pkdeva" target="_blank" rel="noopener noreferrer">linkedin.com/in/pkdeva <ArrowUpRight size={14} /></a></div></div><div className="contact-form">{sent ? <div className="form-success"><h3>Message received.</h3><p>I’ll get back to you soon.</p></div> : <form onSubmit={handleSubmit}><div className="form-field"><label htmlFor="name">Name</label><input id="name" name="name" required placeholder="Your name" /></div><div className="form-field"><label htmlFor="email">Email</label><input id="email" name="email" type="email" required placeholder="you@example.com" /></div><div className="form-field"><label htmlFor="subject">Subject</label><input id="subject" name="subject" required placeholder="A quick hello" /></div><div className="form-field"><label htmlFor="message">Message</label><textarea id="message" name="message" required rows={4} placeholder="Tell me what you are building..." /></div><button className="button-primary form-submit" type="submit" disabled={isSubmitting}>{isSubmitting ? 'Sending...' : 'Send message'} <ArrowUpRight size={16} /></button></form>}</div></div></div></section>;
};
export default Contact;
